version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9197:9197"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/dedeuniversauth3
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      SPRING_MAIL_HOST: localhost
      SPRING_MAIL_PORT: 9025
      JWT_SECRET: 908f36e92dc66d97d5933f0e6371493cb4fc05b1aa8f8de64014732472303a7a
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dedeuniversauth3
    ports:
      - "3306:3306"
